---
# tasks file for koji-builder
- name: Main | Install {{ koji_builder_package }}
  package:
    name: "{{ koji_builder_package }}"
    state: present
  tags:
    - builder
    - builder-package

- name: Main | Install koji-builder deps
  package:
    name: "{{ item }}"
    state: present
  with_items: ["yum", "python2-createrepo_c", "rpm-build", "createrepo*"]
  tags:
    - builder-package

- name: Configure /etc/kojid/kojid.conf
  template:
    src: kojid.conf.j2
    dest: /etc/kojid/kojid.conf
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart kojid
  tags:
    - builder

- include: check_certificates.yml
  vars:
    cert_file: "{{ item }}"
  with_items:
    - "{{ koji_builder_pem }}"
    - "{{ koji_builder_ca }}"
    - "{{ koji_builder_serverca }}"

- name: "Ensure kojid is running"
  service:
    name: kojid
    state: started
    enabled: yes
  tags:
    - builder
    - koji-service
